[[plugins]]
  package = "@netlify/plugin-nextjs"

[build]
command = "npm run build"
node_bundler = "esbuild"
external_node_modules = ["lodash", "axios"]
# Other build settings
[[headers]]
  for = "/_next/image/*"

  [headers.values]
    Strict-Transport-Security = "max-age=31536000"
    X-Test = 'foobar'